import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'testing';

  items = [
    {
      "id": 3,
      "NameAplication": "TP Compass",
      "desAp": "Puedes encontrar el acceso a los informes según tu perfil",
      "ColorBase": "#3046B0",
      "ColorGradiente": null,
      "idvpn": 1,
      "desVpn": "Con Vpn",
      "link": "https://tpcompass.teleperformance.co/login",
      "IdTypePlatform": 1,
      "TypePlatform": "Aplicación o Plataforma",
      "Keywords": "Reporteria,reporte",
      "publicado": 1,
      "marcado": "app",
      "isFavorite": true,
      "Icon": ""
    },
    {
      "id": 4,
      "NameAplication": "TP Bonus",
      "desAp": "Puede encontrar las bonificaciones monetarias de acuerdo a los resultados de los (KPIs) definidos para ti.",
      "ColorBase": "#780096",
      "ColorGradiente": null,
      "idvpn": 3,
      "desVpn": "Con y sin Vpn",
      "link": "https://tpcompass.teleperformance.co/container/home/16",
      "IdTypePlatform": 1,
      "TypePlatform": "Aplicación o Plataforma",
      "Keywords": "Bonificación ",
      "publicado": 1,
      "marcado": "app",
      "isFavorite": true,
      "Icon": ""
    },
    {
      "id": 6,
      "NameAplication": "MyTP Learning",
      "desAp": "Consigue entrenamiento y experiencias educativas para incrementar tus conocimientos y habilidades.",
      "ColorBase": "#F2711C",
      "ColorGradiente": null,
      "idvpn": 3,
      "desVpn": "Con y sin Vpn",
      "link": "https://teleperformance-mytp.sabacloud.com/",
      "IdTypePlatform": 1,
      "TypePlatform": "Aplicación o Plataforma",
      "Keywords": "Cursos, Formación ",
      "publicado": 1,
      "marcado": "app",
      "Icon": ""
    },
    {
      "id": 24,
      "NameAplication": "Epical",
      "desAp": "Epical",
      "ColorBase": "#0087FF",
      "ColorGradiente": null,
      "idvpn": 3,
      "desVpn": "Con y sin Vpn",
      "link": "https://epicalgames.teleperformance.co",
      "IdTypePlatform": 1,
      "TypePlatform": "Aplicación o Plataforma",
      "Keywords": "Prueba 1,carlos",
      "publicado": 1,
      "marcado": "app",
      "Icon": ""
    },
    {
      "id": 29,
      "NameAplication": "Chat IT",
      "desAp": "Descripción Prueba 5",
      "ColorBase": "#00D769",
      "ColorGradiente": null,
      "idvpn": 3,
      "desVpn": "Con y sin Vpn",
      "link": "www.google.com",
      "IdTypePlatform": 1,
      "TypePlatform": "Aplicación o Plataforma",
      "Keywords": "Prueba 5",
      "publicado": 1,
      "marcado": "app",
      "Icon": ""
    },
    {
      "id": 34,
      "NameAplication": "Nice IEX",
      "desAp": "Es una herramienta de gestión de WFM, genera forecast, genera horarios, y permite la administración y seguimiento de estos.",
      "ColorBase": "#FF5C00",
      "ColorGradiente": null,
      "idvpn": 3,
      "desVpn": "Con y sin Vpn",
      "link": null,
      "IdTypePlatform": 1,
      "TypePlatform": "Aplicación o Plataforma",
      "Keywords": "NICE,IEX,WFM,Workforce,Horarios,Schedules,Forecast,previsión,RTA,real time,tiempo real,adherencia",
      "publicado": 1,
      "marcado": "app",
      "isFavorite": true,
      "Icon": ""
    },
    {
      "id": 50,
      "NameAplication": "Test 2411",
      "desAp": "Descripción Test 2411",
      "ColorBase": "#00D769",
      "ColorGradiente": null,
      "idvpn": 1,
      "desVpn": "Con Vpn",
      "link": "www.google.com",
      "IdTypePlatform": 2,
      "TypePlatform": "Funcionalidad",
      "Keywords": "Test 2411",
      "publicado": 1,
      "marcado": "app",
      "Icon": ""
    },
    {
      "id": 51,
      "NameAplication": "Test 24112022",
      "desAp": "ghfghjg",
      "ColorBase": "#00D769",
      "ColorGradiente": null,
      "idvpn": 3,
      "desVpn": "Con y sin Vpn",
      "link": "www.google.com",
      "IdTypePlatform": 1,
      "TypePlatform": "Aplicación o Plataforma",
      "Keywords": "Test 24112022",
      "publicado": 1,
      "marcado": "app",
      "isFavorite": true,
      "Icon": ""
    },
    {
      "id": 53,
      "NameAplication": "Funcionalidad",
      "desAp": "gfgfg",
      "ColorBase": "#00D769",
      "ColorGradiente": null,
      "idvpn": 1,
      "desVpn": "Con Vpn",
      "link": "www.google.com",
      "IdTypePlatform": 2,
      "TypePlatform": "Funcionalidad",
      "Keywords": "Funcionalidad",
      "publicado": 1,
      "marcado": "app",
      "isFavorite": true,
      "Icon": ""
    },
    {
      "id": 2,
      "NameAplication": "CCMS",
      "desAp": "Herramienta en la que podrás realizar diferentes tipos de gestiones de los empleados, del flujo de trabajo, análisis y planificación laboral, de calidad, TOPS BEST y nómina. ",
      "ColorBase": "#780096",
      "ColorGradiente": "#F2711C",
      "idvpn": 1,
      "desVpn": "Con Vpn",
      "link": "https://www.seadc.ccms.teleperformance.com",
      "IdTypePlatform": 1,
      "TypePlatform": "Aplicación o Plataforma",
      "Keywords": "Comunicado, Horario programado,Monitoreo,TOPS Console, TOPS, BEST,perfil, rol",
      "publicado": 1,
      "marcado": "imp",
      "isFavorite": true,
      "Icon": ""
    }
  ];
}
